[project]
authors = ["Cordero Core <127983572+uwcdc@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "biodiversity-horizons"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
precommit-install = "pre-commit install"
precommit-all = "pre-commit run --all-files"
precommit = "pre-commit run"

[dependencies]
jupyterlab = ">=4.3.0,<5"
pixi-kernel = ">=0.5.1,<0.6"
xarray = ">=2024.10.0,<2025"
s3fs = ">=2024.10.0,<2025"
fsspec = ">=2024.10.0,<2025"
zarr = ">=2.18.3,<3"
pre-commit = ">=4.1.0,<5"
